"""
Django development settings for django-htmx-starter project.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Load .env file for development
load_dotenv(Path(__file__).resolve().parent.parent.parent / ".env")

from .base import *  # noqa: F401, F403

# Secret key from environment (generated by start.sh if missing)
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-dev-key-change-me-in-production"
)

# Debug mode
DEBUG = True

# .local allows LAN-shareable subdomains (e.g., myproject.hostname.local for dade)
ALLOWED_HOSTS = ["localhost", "127.0.0.1", ".localhost", ".local"]

# Add debug toolbar for development
INSTALLED_APPS += [  # noqa: F405
    "debug_toolbar",
]

MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")  # noqa: F405

# Debug toolbar settings
INTERNAL_IPS = [
    "127.0.0.1",
]

# For django-allauth in development, allow HTTP (if enabled)
if SOCIAL_AUTH_ENABLED:  # noqa: F405
    ACCOUNT_DEFAULT_HTTP_PROTOCOL = "http"
